package: naju_event_calendar
version: '0.3.0'
author: NAJU Sachsen
supportpage: https://github.com/NAJU-Sachsen/rex-event-calendar
requires:
  redaxo: '^5.10'
  php: '>=7.1'
  packages:
    naju_group_accounts: '>=0.0.1'
    naju_rex_extensions: '>=0.0.3'
page:
  title: 'Veranstaltungen'
  icon: rex-icon fa-calendar
  subpages:
    list:
      title: 'Kalender'
    add:
      title: 'Hinzufügen'
